spring:
  profiles: test2
server:
  port: 9013
---
spring:
  profiles: test1
server:
  port: 9012
---
spring:
  profiles: test
server:
  port: 9011
---
spring:
  profiles: dev
server:
  port: 9010
---
spring:
  datasource:
    username: root
    password: bdqn
    url: jdbc:mysql://127.0.0.1:3306/invitationmanage?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/static/mapper/**.xml
  type-aliases-package: com.bdqn.demo_spring_boot.pojo